source 'https://rubygems.org'

gem 'gooddata', :git => 'https://github.com/gooddata/gooddata-ruby.git'

gem 'twitter'
gem 'pony'
gem 'terminal-table'
gem 'json'
gem 'json-schema'
gem 'activesupport'
gem 'timecop'
gem 'restforce'
gem 'pry'
gem 'rake'
gem 'rspec'