source 'https://rubygems.org'

gem 'gooddata'
gem 'ffi', '1.9.3'
gem 'terminal-table','1.4.5'
gem "gooddata-dss-jdbc",:platform => "jruby"
gem "gooddata_connectors_base", :path => 'gooddata_connectors_base-s3'
gem "gooddata_connectors_metadata", :path => "gooddata_connectors_metadata-0.0.5"
gem "salesforce_bulk_query",:path => "salesforce_bulk_query-master"
gem "gooddata_connectors_downloader_salesforce", :path => "gooddata_connectors_downloader_salesforce-0.0.2"