source 'https://rubygems.org'

gem 'ffi','1.9.3'
gem 'terminal-table','1.4.5'
gem 'gooddata'
gem "gooddata-dss-jdbc",:platform => "jruby"
gem "gooddata_connectors_base", :path => 'gooddata_connectors_base-s3'
gem "gooddata_connectors_metadata",'0.0.2', :path => "gooddata_connectors_metadata-0.0.2"
gem "gooddata_connectors_ads", :path => "gooddata_connectors_ads-0.0.4"
